set -g default-command "/usr/bin/fish"
set -g default-terminal "xterm-256color"

bind r source-file ~/.tmux.conf

bind-key -T copy-mode Escape send-keys -X cancel
bind-key -T copy-mode q send-keys -X cancel

# Keybindings

# unbind C-b
# unbind '"'
# unbind '%'

set -g prefix C-a
bind C-a send-prefix

bind h split-window -v -c "#{pane_current_path}"
bind v split-window -h -c "#{pane_current_path}"

