set -sg escape-time 0
set-option -g history-limit 50000

set -g default-command "/usr/bin/fish"
set -g default-terminal "xterm-256color"

## Prefix keybindings
# Use default (C-b)
# Most command are rebound to not use the prefix anyway
# set -g prefix C-b
# bind C-b send-prefix

bind r source-file ~/.tmux.conf \; display-message "Config reloaded"

## Window mode
# Use C-w + key for window shortcuts instead of $prefix + key
bind -n C-w switch-client -T window-mode
bind -T window-mode Up    if "[ $(tmux display -p '#{pane_current_command}') = vim ]" "send-keys C-w Up" "select-pane -U" 
bind -T window-mode Down  if "[ $(tmux display -p '#{pane_current_command}') = vim ]" "send-keys C-w Down" "select-pane -D"
bind -T window-mode Left  if "[ $(tmux display -p '#{pane_current_command}') = vim ]" "send-keys C-w Left" "select-pane -L"
bind -T window-mode Right if "[ $(tmux display -p '#{pane_current_command}') = vim ]" "send-keys C-w Right" "select-pane -R"

bind -r -T window-mode C-Up    resize-pane -U 2
bind -r -T window-mode C-Down  resize-pane -D 2
bind -r -T window-mode C-Left  resize-pane -L 5
bind -r -T window-mode C-Right resize-pane -R 5

bind -T window-mode h split-window -v -c "#{pane_current_path}"
bind -T window-mode v split-window -h -c "#{pane_current_path}"

## Copy mode
# Enter copy mode
bind -n C-a copy-mode
bind -n -T copy-mode Escape send -X cancel
bind -n -T copy-mode q send -X cancel

# Use vim-like keys for copying
bind -n -T copy-mode 'v' send -X begin-selection
bind -n -T copy-mode 'y' send -X copy-pipe-and-cancel "xclip -selection clipboar" \; display-message "Copied to system clipboard."
bind -n -T copy-mode 'b' send -X rectangle-toggle
