set-option global tabstop 4
set-option global indentwidth 4
set-option global scrolloff 3,3

add-highlighter global/ number-lines -separator '  '
set-face global LineNumbers bright-black
set-face global LineNumberCursor bright-black
set-face global LineNumberWrapped bright-black

set-face global MenuForeground black@MenuForeground
set-face global MenuBackground black@MenuBackground

set-face global PrimarySelection black,blue
set-face global SecondarySelection black,cyan

hook global NormalKey y|d|c %{ nop %sh{
    printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}

map global insert <c-left> '<a-;>b<a-;>;'
map global insert <c-right> '<a-;>e<a-;>;'
map global normal <c-left> 'b'
map global normal <c-right> 'e'
map global normal <c-s-left> 'B'
map global normal <c-s-right> 'E'

map global insert <pageup> '<a-;><pageup>'
map global insert <pagedown> '<a-;><pagedown>'

# Enter insert mode where the cursor is intead of at the start of the selection.
# Note that this also discards the selection.
map global normal i ';i'

map global normal p '!xsel --output --clipboard<ret>'
map global normal P '<a-!>xsel --output --clipboard<ret>'

# Trim trailing whitespace on save
hook global BufWritePre .* %{ try %{ execute-keys -draft \%s\h+$<ret>d } }

# Source the plugin manager
source "%val{config}/plugins/plug.kak/rc/plug.kak"

plug "andreyorst/smarttab.kak"

# smarttab
hook global WinCreate .* expandtab
hook global ModuleLoaded smarttab %{
    set-option global softtabstop 4
}
