newline_style = "Unix"
max_width = 120
comment_width = 100

merge_derives = false
use_field_init_shorthand = true
wrap_comments = true

# Unstable
unstable_features = true
format_macro_matchers = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
