background #282b2c
cursor #777777

# black
color0 #222222
color8 #767676

# red
color1 #cc0000
color9 #ef2929

# green
color2  #4e9a06
color10 #8ae234

# yellow
color3  #c4b000
color11 #ffee44

# blue
color4  #3473cc
color12 #729fff

# magenta
color5  #85508b
color13 #bb7fb8

# cyan
color6  #06a8aa
color14 #34e2e2

# white
color7  #d3d7cf
color15 #eeeeee

